<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Asset Tag Stickers</title>
    <style>
        @page {
            margin: 0.15in;
            size: 4in 6in;
        }
        body { font-family: 'Helvetica', Arial, sans-serif; font-size: 8.5pt; color: #000; }
        table { width: 100%; border-collapse: collapse; }
        .label-page { page-break-after: always; }
        .label-page:last-child { page-break-after: auto; }
        .header-row { border-bottom: 2pt solid #000; padding-bottom: 4pt; margin-bottom: 6pt; }
        .logo-cell { width: 0.7in; vertical-align: middle; }
        .logo-cell img { width: 0.55in; height: 0.55in; }
        .org-cell { vertical-align: middle; padding-left: 6pt; }
        .org-title { font-size: 9pt; font-weight: bold; margin: 0; }
        .org-subtitle { font-size: 6.5pt; margin: 1pt 0 0; color: #333; }
        .piece-badge { border: 1.5pt solid #000; text-align: center; padding: 5pt 0; font-size: 16pt; font-weight: bold; letter-spacing: 0.5pt; margin: 6pt 0; }
        .service-line { text-align: center; font-weight: bold; font-size: 10pt; text-transform: uppercase; border-top: 1pt solid #000; border-bottom: 1pt solid #000; padding: 3pt 0; margin: 0 0 6pt; }
        .item-table th, .item-table td { border: 1pt solid #000; padding: 3pt 4pt; font-size: 7.5pt; text-align: left; }
        .item-table th { width: 34%; background: #f2f2f2; }
        .item-table { margin-bottom: 6pt; }
        .qr-footer { border-top: 1pt solid #000; padding-top: 6pt; margin-top: 4pt; }
        .qr-cell { width: 0.95in; text-align: center; vertical-align: top; }
        .qr-cell img { width: 0.85in; height: 0.85in; }
        .doc-cell { vertical-align: top; padding-left: 6pt; font-size: 7pt; }
        .doc-cell p { margin: 1pt 0; }
        .footer-note { text-align: center; font-size: 6pt; color: #555; margin-top: 5pt; font-style: italic; }
    </style>
</head>
<body>

@php
    $denrLogo = 'data:image/jpeg;base64,' . base64_encode(
        file_exists(public_path('images/denr-logo.jpg')) ? file_get_contents(public_path('images/denr-logo.jpg')) : ''
    );
@endphp

@foreach ($pieces as $pieceIndex => $pieceRecord)
@php $pieceNumber = $pieceIndex + 1; @endphp
<div class="label-page">
    <table class="header-row">
        <tr>
            <td class="logo-cell"><img src="{{ $denrLogo }}"></td>
            <td class="org-cell">
                <p class="org-title">DENR &middot; PENRO CATANDUANES</p>
                <p class="org-subtitle">Asset Tracking &middot; LogTrack Insight</p>
            </td>
        </tr>
    </table>

    <div class="piece-badge">PIECE {{ $pieceNumber }} / {{ $totalPieces }}</div>
    <div class="service-line">Asset Tag</div>

    <table class="item-table">
        <tr><th>Asset ID</th><td>{{ $asset->asset_code }}</td></tr>
        <tr><th>AAP No.</th><td>{{ $asset->aap_number ?: '—' }}</td></tr>
        <tr><th>Species</th><td>{{ $pieceRecord->species ?: ($asset->species ?: '—') }}</td></tr>
        <tr>
            <th>Dimension</th>
            <td>
                @if($asset->type->value === 'log' && $pieceRecord->length && $pieceRecord->width && $pieceRecord->height)
                    {{ $pieceRecord->length }} &times; {{ $pieceRecord->width }} &times; {{ $pieceRecord->height }}
                @elseif($pieceRecord->volume_bd_ft)
                    {{ $pieceRecord->volume_bd_ft }} bd.ft
                @else
                    —
                @endif
            </td>
        </tr>
    </table>

    <table class="qr-footer">
        <tr>
            <td class="qr-cell"><img src="{{ $qrPngDataUris[$pieceNumber] ?? '' }}" alt="QR code"></td>
            <td class="doc-cell">
                <p><strong>Date Apprehended:</strong> {{ $asset->incident?->date_of_apprehension?->format('M d, Y') ?? '—' }}</p>
                <p><strong>Place:</strong> {{ $asset->incident?->place_of_apprehension ?? $asset->location_apprehended ?? '—' }}</p>
                <p><strong>Municipality:</strong> {{ $asset->municipality_of_origin }}</p>
            </td>
        </tr>
    </table>

    <p class="footer-note">Scan the QR code to view the live asset record. System-generated by LogTrack Insight.</p>
</div>
@endforeach

</body>
</html>